<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>TextGrab</AssemblyName>
    <Version>0.1.0</Version>
    <Authors>Josh Hills</Authors>
    <Product>TextGrab</Product>
    <ApplicationIcon>Assets/textgrab.ico</ApplicationIcon>
    <RootNamespace>TextGrab.Windows</RootNamespace>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <TieredPGO>true</TieredPGO>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <SelfContained>false</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DebugType>none</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets/textgrab.ico" LogicalName="TextGrab.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../TextGrab.Core/TextGrab.Core.csproj" />
    <ProjectReference Include="../TextGrab.Ocr.Windows/TextGrab.Ocr.Windows.csproj" />
  </ItemGroup>
</Project>
